Develop
AntonAduisky/algososh pull request #2
Opened 2022-10-23 10:20 UTC by AntonAduisky

2022-10-23 11:43 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа!

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализованы все алгоритмы;

### **Но есть несколько замечаний, которые нужно исправить:**

- "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE. (Отметил места в коде);

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app. (App.test.tsx);

- Последовательность фибоначчи:

  - Например, вы ввели 4, тогда на экране должен появиться ряд 1, 1, 2, 3, 5, а у вас будет следующий результат: 0, 1, 1, 2, 3;

- Очередь

  - В целом алгоритм работает верно, но если мы заполним всю очередь, а потом удалим и добавим 2 элемента, то у нас будет ошибка. Поэтому лучше запретить добавлять новые элементы когда вся очередь будет заполнена. Ниже записал видео, чтобы было понятно что я имею ввиду:

  Видео: https://disk.yandex.ru/d/4-4YMXaUx-quIg

- Связный список

  - Если мы удалим все элементы, и потом попытаемся добавить новый элемент, то у нас будет ошибка: https://yadi.sk/d/.Rhn7KkIVloYyBg

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/sorting-page/utils.ts
> +export const randomArr = (min = 3, max = 17) => {
**Надо исправить:** "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +        arr[j].state = ElementStates.Changing;
**Можно лучше:** Здесь и далее. Стоит создать функции сортировки таким образом, чтобы они возвращали набор шагов и далее при отображении алгоритма добавлять паузы между шагами, а не генерировать паузы непосредственно в алгоритме.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/sorting-page/sorting-page.tsx
> +    const arr = newArray.slice();;
**Можно лучше:** Лишняя `;`.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +          max={4}
**Надо исправить:** Вынесите магическое значение в именованные константы.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/stack-page/stack-page.tsx
> +          disabled={!value || loader.removed || stack.getSize() > 5}
**Надо исправить:** Вынесите магическое значение в именованные константы.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +    for (let i = 0; i <= 6; i++) {
**Надо исправить:** Вынесите магические значения в именованные константы.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/queue-page/queue-page.tsx
> +          max={4}
**Надо исправить:** Вынесите магические значения в именованные константы.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/list-page/utils.ts
> +    }
**Можно лучше:** Лучше создать какой-то  отдельный метод для этого.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +              || list.getSize() === 10
**Надо исправить:** "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +            max={4}
**Надо исправить:** "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-10-23 11:43 UTC, ArslanDev666 commented on src/components/list-page/list-page.tsx
> +              || list.getSize() === 10
**Надо исправить:** "Магические" значения лучше вынести в константу. Имена констант принято записывать в стиле UPPER_CASE.

2022-10-23 15:49 UTC, AntonAduisky commented on src/components/fibonacci-page/utils.ts
> +    return false
такой вид и правда лучше , спасибо, но "return true" в условии стояло потому, что иначе любое число до 19 оказывалось не валидным ... Звучит не логично , но факт есть факт, сам не совсем понял почему это именно так работает

2022-10-23 15:55 UTC, ArslanDev666 commented on src/components/fibonacci-page/utils.ts
> +    return false
Посмотрите внимательно на то, как у вас это применяется в disabled. Там должно быть отрицание, чтобы всё работало хорошо.

2022-10-23 16:02 UTC, AntonAduisky commented on src/components/fibonacci-page/utils.ts
> +      if(number <= 0 || number > 19) return true;
![image](https://user-images.githubusercontent.com/92021789/197402641-5a03d737-d7dd-410c-8412-018ad5d7270c.png)
правильно понял , что абсолютно любая константа записыввается в upper_case ? или есть какие-то исключения?

2022-10-23 16:09 UTC, ArslanDev666 commented on src/components/fibonacci-page/utils.ts
> +      if(number <= 0 || number > 19) return true;
Не совсем, сейчас не смогу найти нужного материла, спросите у наставника.

2022-10-23 18:09 UTC, AntonAduisky commented on src/components/list-page/list-page.tsx
> +              || list.getSize() === 10
как должно быть реализовано удаление элементов из списка ?(ps: касаемо ошибки в консоли при полном удалении списка) Надо дизейблить кнопки удаления если в связном-списке находится один элемент или надо допускать возможность удалить полностью все элементы?(в таком случае текст на кнопках становится не логичным тк как добавлять в тейл или хед если их не существует)) ) В любом случае учел эти оба варианта . Спасибо за качественное ревью

2022-10-24 14:56 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа! Практически все замечания были исправлены.

### **Вы молодец!**

- Вы молодец, что добавляете комментарии к коду, это очень круто!

### **Но есть несколько замечаний, которые нужно исправить:**

- Очередь

  - Если мы заполним всю очередь, а потом удалим все элементы и добавим 1 элемент, то у нас будет неверное отображение. Ниже записал видео, чтобы было понятно что я имею ввиду:

  Видео: https://disk.yandex.ru/d/hdm1kpk0wWPv4A

- Связный список

  - При добавлении в head элемент должен появиться над первым элементом вместо надписи head, затем он занимает первое место в списке и на долю секунды выделяется зелёным цветом. А у вас создаётся отдельный элемент. точно также должно действовать добавление элемента в tail (там свои действия, но главное чтобы значение сначала было над старым элементом, а потом перешло в новый).

    1 шаг - https://yadi.sk/d/FTrWdkkDOmqdYg
    2 шаг - https://yadi.sk/d/4HwRWsE6A4SMGQ

### **Сделает код лучше:**

- Если условие в jsx слишком большое, то следует вынести его в отдельную переменную.

2022-10-24 14:56 UTC, ArslanDev666 commented on src/components/fibonacci-page/fibonacci-page.tsx
> +        <Button type="submit" text="рассчитать" disabled={checkValidity(number) || !number} isLoader={loader} />
**Надо исправить:** В прошлом ревью было замечание: https://github.com/AntonAduisky/algososh/pull/2#discussion_r1002689844. Чтобы функция (комментарий замечания) корректно отрабатывала, то достаточно сделать вот так: 

```js
  <Button {...} disabled={!checkValidity(number) || !number} /> 
```

Мы делаем отрицание, т.е если переменная валидна (true), мы делаем отрицание и тогда у нас disabled=false. Что говорит кнопке, не нужно блокироваться. И точно также наоборот.

2022-10-24 19:11 UTC, AntonAduisky commented on src/components/fibonacci-page/fibonacci-page.tsx
> +        <Button type="submit" text="рассчитать" disabled={checkValidity(number) || !number} isLoader={loader} />
был не внимателен, спасибо за разьяснение и качественное ревью в целом ;)

2022-10-25 00:54 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте! Все замечания с прошлого ревью были исправлены!

### **Вы молодец! Работа принята, удачи в дальнейшем обучении.**

### **Сделает код лучше:**

- Лучше реализовывать удаление таймера/интервала при размонтировании компонента, иначе возможны ошибки/баги когда компонент размонтируется, а таймер всё равно сработает.

- Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

2022-10-25 19:47 UTC, merged